# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book_authors.Book'),
            preserve_default=False,
        ),
    ]
